---
layout: collection-browser-doc
title: Contributing
categories:
  - Community
excerpt: >-
  Terragrunt is an open source project, and contributions from the community are very welcome!
tags: ["contributing", "community"]
order: 300
nav_title: Documentation
nav_title_link: /documentation/
---
:page-type: documentation
:page-layout: documentation

:toc:
:toc-placement!:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
toc::[]
endif::[]


== Contributing

Terragrunt is an open source project, and contributions from the community are very welcome! Please check out the link:https://github.com/gruntwork-io/terragrunt/blob/master/CONTRIBUTING.md[Contribution Guidelines] and link:#developing-terragrunt[Developing Terragrunt] for instructions.

== Developing Terragrunt

=== Running locally

To run Terragrunt locally, use the `go run` command:

[source,bash]
----
go run main.go plan
----

=== Dependencies

* Terragrunt uses `dep`, a vendor package management tool for golang. See the dep repo for https://github.com/golang/dep[installation instructions].

=== Running tests

*Note*: The tests in the `dynamodb` folder for Terragrunt run against a real AWS account and will add and remove real data from DynamoDB. DO NOT hit `CTRL+C` while the tests are running, as this will prevent them from cleaning up temporary tables and data in DynamoDB. We are not responsible for any charges you may incur.

Before running the tests, you must configure your link:{site-baseurl}/documentation/features/aws-auth/#aws-credentials[AWS credentials] and link:{site-baseurl}/documentation/features/aws-auth/#aws-iam-policies[AWS IAM policies].

To run all the tests:

[source,bash]
----
go test -v ./...
----

To run only the tests in a specific package, such as the package `remote`:

[source,bash]
----
cd remote
go test -v
----

And to run a specific test, such as `TestToTerraformRemoteConfigArgsNoBackendConfigs` in package `remote`:

[source,bash]
----
cd remote
go test -v -run TestToTerraformRemoteConfigArgsNoBackendConfigs
----

=== Debug logging

If you set the `TERRAGRUNT_DEBUG` environment variable to "true", the stack trace for any error will be printed to stdout when you run the app.

Additionally, newer features introduced in v0.19.0 (such as `locals` and `dependency` blocks) can output more verbose logging if you set the `TG_LOG` environment variable to `debug`.

=== Error handling

In this project, we try to ensure that:

. Every error has a stacktrace. This makes debugging easier.
. Every error generated by our own code (as opposed to errors from Go built-in functions or errors from 3rd party libraries) has a custom type. This makes error handling more precise, as we can decide to handle different types of errors differently.

To accomplish these two goals, we have created an `errors` package that has several helper methods, such as `errors.WithStackTrace(err error)`, which wraps the given `error` in an Error object that contains a stacktrace. Under the hood, the `errors` package is using the https://github.com/go-errors/errors[go-errors] library, but this may change in the future, so the rest of the code should not depend on `go-errors` directly.

Here is how the `errors` package should be used:

. Any time you want to create your own error, create a custom type for it, and when instantiating that type, wrap it with a call to `errors.WithStackTrace`. That way, any time you call a method defined in the Terragrunt code, you know the error it returns already has a stacktrace and you don't have to wrap it yourself.
. Any time you get back an error object from a function built into Go or a 3rd party library, immediately wrap it with `errors.WithStackTrace`. This gives us a stacktrace as close to the source as possible.
. If you need to get back the underlying error, you can use the `errors.IsError` and `errors.Unwrap` functions.

=== Formatting

Every source file in this project should be formatted with `go fmt`. There are few helper scripts and targets in the Makefile that can help with this (mostly taken from the https://github.com/hashicorp/terraform/[terraform repo]):

. `make fmtcheck` Checks to see if all source files are formatted. Exits 1 if there are unformatted files.
. `make fmt` Formats all source files with `gofmt`.
. `make install-pre-commit-hook`
+
Installs a git pre-commit hook that will run all of the source files through `gofmt`.

To ensure that your changes get properly formatted, please install the git pre-commit hook with `make install-pre-commit-hook`.

=== Releasing new versions

To release a new version, just go to the https://github.com/gruntwork-io/terragrunt/releases[Releases Page] and create a new release. The CircleCI job for this repo has been configured to:

. Automatically detect new tags.
. Build binaries for every OS using that tag as a version number.
. Upload the binaries to the release in GitHub.

See `.circleci/config.yml` for details.
